DROP DATABASE IF EXISTS perfectpets;
CREATE DATABASE IF NOT EXISTS perfectpets;
USE perfectpets;

CREATE TABLE clinic (
clinicNo INT PRIMARY KEY
);

CREATE TABLE staff (
staffNo INT PRIMARY KEY,
manager_status BOOL DEFAULT FALSE,
clinicNo INT NOT NULL,
FOREIGN KEY (clinicNo) REFERENCES clinic(clinicNo)
	ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE petOwner (
ownerNo INT PRIMARY KEY,
clinicNo INT NOT NULL,
FOREIGN KEY (clinicNo) REFERENCES clinic(clinicNo)
	ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE pet (
petNo INT PRIMARY KEY,
ownerNo INT NOT NULL,
FOREIGN KEY (ownerNo) REFERENCES petOwner(ownerNo)
	ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE examination (
examNo INT PRIMARY KEY,
petNo INT NOT NULL,
FOREIGN KEY (petNo) REFERENCES pet(petNo)
	ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE treatment (
treatNo INT PRIMARY KEY,
examNo INT NOT NULL,
FOREIGN KEY (examNo) REFERENCES examination(examNo)
	ON UPDATE CASCADE ON DELETE RESTRICT
);